In [3]:
import pandas as pd

In [12]:
household = pd.read_csv('~/Qsync/整理/Work/Uganda RCT/ISASimple_Gates_LLINE-UP_rct_RSRC_households.txt', sep='\t')

/usr/local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (29,35,54,79,81,84,97,98,112,121,122,123) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [13]:
household.describe()

,Acres [EUPATH_0000026],Bednet count [EUPATH_0020225],Bednets per person [EUPATH_0020227],Bloodfed Anopheles funestus count [EUPATH_0000192],Bloodfed Anopheles gambiae count [EUPATH_0000193],Enumeration area ID [EUPATH_0044123],Female Anopheles count [EUPATH_0000135],Female Anopheles funestus count [EUPATH_0000136],Female Anopheles gambiae count [EUPATH_0000137],Female non-Anopheline count [EUPATH_0044116],...,Semigravid Anopheles funestus count [EUPATH_0044103],Semigravid Anopheles gambiae count [EUPATH_0044105],Sleeping places count [EUPATH_0000201],Sleeping rooms in dwelling [EUPATH_0000025],Sleeping rooms used last night [EUPATH_0044119],Study timepoint [OBI_0001508],UCC LLIN count [EUPATH_0044146],UCC LLIN wave [EUPATH_0044168],Unfed Anopheles funestus count [EUPATH_0000204],Unfed Anopheles gambiae count [EUPATH_0000205]
count,20668.000000,20792.000000,20792.000000,721.000000,721.000000,20792.000000,4143.000000,4143.000000,4143.000000,4143.000000,...,721.000000,721.000000,20790.000000,20790.000000,997.000000,20792.000000,14583.000000,20792.000000,721.000000,721.000000
mean,12.002540,2.405444,0.454338,1.511789,3.456311,5.500577,1.788800,0.504465,1.280714,3.143857,...,0.420250,1.553398,3.411736,2.255026,2.052156,9.002309,3.211616,3.451905,0.482663,1.529820
std,284.025083,1.592907,0.278261,6.049122,11.576609,2.872434,11.761699,4.148489,10.584813,11.746603,...,2.221006,6.315786,1.938140,1.056212,1.035169,6.708365,1.516764,0.705554,2.422703,8.128449
min,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
25%,1.000000,1.000000,0.290000,0.000000,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,2.000000,1.000000,1.000000,6.000000,2.000000,3.000000,0.000000,0.000000
50%,2.000000,2.000000,0.500000,0.000000,1.000000,6.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,3.000000,2.000000,2.000000,12.000000,3.000000,4.000000,0.000000,0.000000
75%,3.000000,3.000000,0.600000,1.000000,2.000000,8.000000,0.000000,0.000000,0.000000,2.000000,...,0.000000,1.000000,4.000000,3.000000,3.000000,18.000000,4.000000,4.000000,0.000000,1.000000
max,10000.000000,16.000000,3.330000,101.000000,223.000000,10.000000,401.000000,144.000000,395.000000,246.000000,...,50.000000,81.000000,25.000000,11.000000,6.000000,18.000000,18.000000,4.000000,50.000000,141.000000

In [14]:
household.head(10)

,Household_Id,Community_Id,1 bednet per 2 people [EUPATH_0020219],1 ITN per 2 people [EUPATH_0044135],Acres [EUPATH_0000026],Acres categorization [EUPATH_0020221],Air bricks [EUPATH_0000018],Asked permission for IRS in last 12 months [EUPATH_0020224],Bank account [EUPATH_0000167],Bed [ENVO_00000501],...,UCC LLIN instructions received [EUPATH_0044143],UCC LLIN received [EUPATH_0044142],UCC LLIN type [EUPATH_0044148],UCC LLIN wave [EUPATH_0044168],Unfed Anopheles funestus count [EUPATH_0000204],Unfed Anopheles gambiae count [EUPATH_0000205],Wall material [EUPATH_0000009],Watch [EUPATH_0000186],Windows [EUPATH_0025050],Windows covered [EUPATH_0020212]
0,h_100101003,c_1,No,No,3.0,3. >1 to 3 acres,NaN,No,No,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Mud and poles,No,Yes,Yes
1,h_100101007,c_1,No,No,1.0,2. 1 acre or less,"Yes, over all windows",No,No,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Mud and poles,No,Yes,Yes
2,h_100101011,c_1,No,No,2.0,3. >1 to 3 acres,NaN,No,No,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Burned bricks with plaster or cement,No,Yes,Yes
3,h_100101017,c_1,No,No,2.0,3. >1 to 3 acres,NaN,No,No,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Mud and poles,No,Yes,Yes
4,h_100101027,c_1,No,No,8.0,4. 4 acres or more,NaN,No,No,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Mud and poles,No,Yes,Yes
5,h_100102011,c_1,Yes,Yes,3.0,3. >1 to 3 acres,NaN,No,No,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Burned bricks with plaster or cement,No,Yes,Yes
6,h_100102013,c_1,No,No,3.0,3. >1 to 3 acres,"Yes, over all windows",No,Yes,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Burned bricks with plaster or cement,Yes,Yes,Yes
7,h_100102021,c_1,No,No,50.0,4. 4 acres or more,NaN,No,No,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Burned bricks with plaster or cement,No,Yes,Yes
8,h_100102025,c_1,No,No,3.0,3. >1 to 3 acres,NaN,No,No,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Mud and poles,No,Yes,Yes
9,h_100102029,c_1,No,No,1.0,2. 1 acre or less,NaN,No,No,Yes,...,NaN,NaN,NaN,4,NaN,NaN,Mud and poles,No,Yes,No

In [15]:
observation = pd.read_csv('~/Qsync/整理/Work/Uganda RCT/ISASimple_Gates_LLINE-UP_rct_RSRC_observations.txt', sep='\t')

In [16]:
observation

,Observation_Id,Participant_Id,Household_Id,Age [OBI_0001169],Age <2 years [EUPATH_0044139],Age category [EUPATH_0040020],Bednet last night [EUPATH_0025013],Febrile [EUPATH_0000097],ITN last night [EUPATH_0000216],Observation date [EUPATH_0004991],Study timepoint [OBI_0001508]
0,o_10010100301_00m_1,10010100301_00m,h_100101003,45.00,No,16 years of age or older,Yes,NaN,Yes,13-05-2017,0
1,o_10010100302_00m_1,10010100302_00m,h_100101003,35.00,No,16 years of age or older,Yes,NaN,Yes,13-05-2017,0
2,o_10010100303_00m_1,10010100303_00m,h_100101003,19.00,No,16 years of age or older,No,NaN,No,13-05-2017,0
3,o_10010100304_00m_1,10010100304_00m,h_100101003,18.00,No,16 years of age or older,No,NaN,No,13-05-2017,0
4,o_10010100305_00m_1,10010100305_00m,h_100101003,16.00,No,16 years of age or older,No,NaN,No,13-05-2017,0
...,...,...,...,...,...,...,...,...,...,...,...
115537,o_41041009303_18m_4,41041009303_18m,h_410410093,17.00,No,16 years of age or older,Yes,NaN,Yes,11-11-2018,18
115538,o_41041009304_18m_4,41041009304_18m,h_410410093,12.00,No,5 - 15 years of age,Yes,NaN,Yes,11-11-2018,18
115539,o_41041009305_18m_4,41041009305_18m,h_410410093,9.00,No,5 - 15 years of age,Yes,Yes,Yes,11-11-2018,18
115540,o_41041009306_18m_4,41041009306_18m,h_410410093,6.00,No,5 - 15 years of age,Yes,No,Yes,11-11-2018,18
115541,o_41041009307_18m_4,41041009307_18m,h_410410093,0.67,Yes,Fewer than 5 years of age,Yes,NaN,Yes,11-11-2018,18

In [17]:
metadata = pd.read_csv('~/Qsync/整理/Work/Uganda RCT/ISASimple_Gates_LLINE-UP_rct_RSRC_ontologyMetadata.txt', sep='\t')

In [18]:
metadata

,iri,label,type,parentlabel,category,definition,min,max,average,upper_quartile,lower_quartile,number_distinct_values,distinct_values,variable,replaces
0,ENVO_00000004,Country,string,Geographic location,Household,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Uganda|,"hh_00m::country,hh_06m::country,hh_12m::countr...",NaN
1,ENVO_00000501,Bed,string,Assets,Household,Whether the household had a bed.,NaN,NaN,NaN,NaN,NaN,4.0,Don&apos;t know|No|Refused to answer|Yes|,"hh_00m::bed,hh_06m::bed,hh_12m::bed,hh_18m::bed",NaN
2,ENVO_00003064,Drinking water source,string,Household water,Household,Main source of drinking water for members of t...,NaN,NaN,NaN,NaN,NaN,18.0,Borehole|Bottled water|Dam|Open public well|Op...,"hh_00m::swater,hh_06m::otherscs,hh_06m::swater...",NaN
3,ENVO_01000577,Radio,string,Assets,Household,Whether the household had a radio.,NaN,NaN,NaN,NaN,NaN,2.0,No|Yes|,"hh_00m::radio,hh_06m::radio,hh_12m::radio,hh_1...",NaN
4,ENVO_01000578,Cassette player,string,Assets,Household,Whether the household had a cassette player.,NaN,NaN,NaN,NaN,NaN,3.0,No|Refused to answer|Yes|,"hh_00m::cassette,hh_06m::cassette,hh_12m::cass...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201,OBI_0002649,Blood microbiology test,NaN,Laboratory test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,OBI_0400065,Lighting source,string,Dwelling facilities,Household,Main source of artificial lighting for the hou...,NaN,NaN,NaN,NaN,NaN,12.0,Burned tires|Candles|Electricity|Firewood or c...,"hh_00m::senergy,hh_06m::senergy,hh_12m::senerg...",NaN
203,OGMS_0000056,Laboratory test,NaN,Sample,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
204,PATO_0000047,Sex,string,Demographics,Participant,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Female|Male|,"hh_member_00m::gender,hh_member_06m::gender,hh...",NaN
205,PCO_0000024,Household,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
participants = pd.read_csv('~/Qsync/整理/Work/Uganda RCT/ISASimple_Gates_LLINE-UP_rct_RSRC_participants.txt', sep='\t')

In [21]:
participants

,Participant_Id,Household_Id,Eligible for clinical survey [EUPATH_0044101],Household head age categorization (years) [EUPATH_0044151],Household head's sex [EUPATH_0044152],Relationship to household head [EUPATH_0000376],Relationship to household head categorization [EUPATH_0044138],Sex [PATO_0000047]
0,21020705606_06m,h_210207056,Yes,NaN,NaN,Grandson / granddaughter / great-grandson / gr...,2nd degree relative,Male
1,30120506002_12m,h_301205060,No,NaN,NaN,Husband / wife,1st degree relative,Female
2,30930107902_12m,h_309301079,No,NaN,NaN,Husband / wife,1st degree relative,Female
3,30270904603_12m,h_302709046,Yes,NaN,NaN,Son / daughter,1st degree relative,Female
4,30710405403_12m,h_307104054,Yes,NaN,NaN,Son / daughter,1st degree relative,Female
...,...,...,...,...,...,...,...,...
115537,10800405701_00m,h_108004057,No,40-49 years,Male,Self (household head),Head of household,Male
115538,30640503904_12m,h_306405039,Yes,NaN,NaN,Son / daughter,1st degree relative,Female
115539,40130401001_18m,h_401304010,No,NaN,NaN,Self (household head),Head of household,Female
115540,20340700604_06m,h_203407006,No,NaN,NaN,Son / daughter,1st degree relative,Male
115541,10840209303_00m,h_108402093,Yes,30-39 years,Male,Son / daughter,1st degree relative,Male

In [22]:
participants.describe()

,Participant_Id,Household_Id,Eligible for clinical survey [EUPATH_0044101],Household head age categorization (years) [EUPATH_0044151],Household head's sex [EUPATH_0044152],Relationship to household head [EUPATH_0000376],Relationship to household head categorization [EUPATH_0044138],Sex [PATO_0000047]
count,115542,115542,115542,29612,29612,115542,115542,115542
unique,115542,20792,2,4,2,18,4,2
top,30710209013_12m,h_309102095,No,30-39 years,Male,Son / daughter,1st degree relative,Female
freq,1,27,72857,8919,23782,64322,81568,61453

In [24]:
samples = pd.read_csv('~/Qsync/整理/Work/Uganda RCT/ISASimple_Gates_LLINE-UP_rct_RSRC_samples.txt', sep='\t')

In [25]:
samples

,Sample_Id,Observation_Id,Participant_Id,Household_Id,Anemia (hemoglobin less than 10g/dL) [EUPATH_0020209],Anemia (hemoglobin less than 11g/dL) [EUPATH_0011161],Anemia (hemoglobin less than 8g/dL) [EUPATH_0044112],Blood smear performed [EUPATH_0041029],Consent for lab testing [EUPATH_0044111],Hemoglobin (g/dL) [EUPATH_0000047],Hemoglobin measurement performed [EUPATH_0027005],"Plasmodium asexual stages (per uL blood), by microscopy [EUPATH_0000092]","Plasmodium falciparum gametocytes, by microscopy [EUPATH_0027010]","Plasmodium, by RDT [EUPATH_0024217]","Plasmodium, by thick smear microscopy [EUPATH_0024314]",RDT performed [EUPATH_0027004]
0,s_10010100301_00m_1,o_10010100301_00m_1,10010100301_00m,h_100101003,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion criteria,Did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...
1,s_10010100302_00m_1,o_10010100302_00m_1,10010100302_00m,h_100101003,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion criteria,Did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...
2,s_10010100303_00m_1,o_10010100303_00m_1,10010100303_00m,h_100101003,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion criteria,Did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...
3,s_10010100304_00m_1,o_10010100304_00m_1,10010100304_00m,h_100101003,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion criteria,Did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...
4,s_10010100305_00m_1,o_10010100305_00m_1,10010100305_00m,h_100101003,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion criteria,Did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115537,s_41041009303_18m_4,o_41041009303_18m_4,41041009303_18m,h_410410093,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion criteria,Did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...
115538,s_41041009304_18m_4,o_41041009304_18m_4,41041009304_18m,h_410410093,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion criteria,Did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...
115539,s_41041009305_18m_4,o_41041009305_18m_4,41041009305_18m,h_410410093,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Yes,Yes,NaN,Did not consent / did not meet inclusion criteria,0.0,Yes,No,No,Yes
115540,s_41041009306_18m_4,o_41041009306_18m_4,41041009306_18m,h_410410093,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Yes,Yes,NaN,Did not consent / did not meet inclusion criteria,0.0,No,Did not consent / did not meet inclusion crite...,No,Did not consent / did not meet inclusion crite...
115541,s_41041009307_18m_4,o_41041009307_18m_4,41041009307_18m,h_410410093,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion criteria,Did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion criteria,NaN,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...,Did not consent / did not meet inclusion crite...

In [26]:
samples.describe()

,Hemoglobin (g/dL) [EUPATH_0000047],"Plasmodium asexual stages (per uL blood), by microscopy [EUPATH_0000092]"
count,13747.000000,32100.000000
mean,11.770685,1650.403769
std,1.468040,11906.090693
min,1.900000,0.000000
25%,10.900000,0.000000
50%,12.000000,0.000000
75%,12.700000,0.000000
max,20.300000,674000.000000